### PR TITLE
fix: the showcase section on homepage for iPhone 5/SE

### LINKED ISSUE #696: Homepage display broken on iPhone5/SE
## Description

The homepage of nextjs is broken on iPhone 5/SE, basically on all sizes below 330 pixels.

### Steps to reproduce

1. Go to the home page of https://nextjs.org/ on iPhone 5/SE
2. Scroll down to the **Who’s Using Next.js** section
3. You will see the images are moving out of the normal display

### Expected result

1. Changed the flex rule from **flex: 0 0 50%** to **flex: 0 0 100%** for the container of figure element.
2. I have given width of **100%** to the container of image 

expected-result

### Actual result

Fixed width of 330 pixel is given to container of image

actual-result

### PR DESCRIPTION
**Pull request by abhishekjakhar**
### DESCRIPTION
The homepage of website is broken on iPhone 5/SE(320px), basically on all sizes below 330px, because the images in **Who’s Using Next.js** section are given minimum width of 330px due to which they are moving out of the normal display on sizes below 330px.

#### Fix(Expected)
expected

#### Bug(Actual)
actual

### HOW TO TEST

- Go to home page(http://localhost:3000)
- Scroll down to the Who’s Using Next.js section
- The image should not move out of the screen horizontally

Fixes #696

### CODE REVIEW

File: components/image.js [hunk 1]
```diff
@@ -116,8 +116,14 @@ class Image extends Component {
               }
               .container {
                 margin: 0 auto;
+                width: ${width}px;
```
Comment (lfades) [inline components/image.js:119]:
```suggestion
                ${width ? `width: ${width}px;`: ''}
```

**Comment by abhishekjakhar** [comment]
@lfades You're welcome 👍
